### ISSUE TITLE
解决 float 的父容器高度塌陷

### ISSUE THREAD

**Issue by LahmYing** [LahmYing/front-end-tools#1]
### 浮动缺点
父 div 塌陷，高度→0

### 解决原理
尾部加入一个 block 元素，将其设 clear:both，它不浮动，于是撑起父 div 的高度

#### 伪元素
```html
<div id="father" class="clearfix">
    <div id="son"></div>
</div>
``` 
```css
      /*ie6 7 不支持伪元素*/
      .clearfix:after {
        content: '';
        display: block;
        clear: both;
        height:0;
        line-height:0;
        visibility:hidden;//允许浏览器渲染它，但是不显示出来
      }
```
