### ISSUE TITLE
百分比布局

### ISSUE THREAD

**Issue by LahmYing** [LahmYing/front-end-tools#2]
### 百分比能够设置的属性
width、height、padding、margin。
其他属性比如 border、font-size 不能用百分比设置的

### 映射
// width，指的是父元素 width 的百分之多少
// height，那么指的是父元素 height 的百分之多少
// padding，那么指的是父元素 width 的百分之多少，无论是水平的 padding 还是竖直的 padding
// margin，那么指的是父元素 width 的百分之多少，无论是水平的 margin 还是竖直的 margin

```css
div{
  width:200px;
  height:300px;
  padding:10px;
}
div p{
  width:50%;
  height:50%;
  padding:10%;
}
```
此时p的真实宽度是多少？
// width = 200px x 50% + 2 x 200px x 10% (左右padding) = 140px
// height = 300px x 50% + 2 x 200px x 10% (上下padding) = 190px
// 此时 p 的真实宽度是 140px*190px
