### ISSUE TITLE
div 居中

### ISSUE THREAD

**Issue by LahmYing** [LahmYing/front-end-tools#4]
### 行内元素
指 inline、inline-block、inline-table、inline-flex 
```css
   .parent{
        /* 在父容器设置文本对齐居中即可 */
        text-align:center;
    }
```

#### 方法1
左右 margin auto，上下 margin 为 0
```css
.child{
    /* 注意，要给宽度 */
    width: 100px;
    /* margin:0 auto; 其实就是 margin: 0 auto 0 auto; 逆时针上右下左。这样简写我都不想吐槽css*/
    margin:0 auto;
}
```

#### 方法2
1.父相子绝，即父 relative 子 absolute，然后开始移动子元素
2.移动父的一半，抵达父的中点
3.移动子的一半，抵达自己的中点
```html
<div class="parent">
  <div class="child">Demo</div>
</div>
<style>
  .child {
    position:absolute;
    /* left 的 % 是相对父的*/
    left:50%;
   /* transform 2D变形的 % 是变自己的 % */
    transform:translateX(-50%);
  }
  .parent {
    position:relative;
  }
</style>
}
```

#### 给定宽度的
1.自己设 relative 然后开始移动自己
2.移动父的一半，抵达父的中点
3.移动子的一半，抵达自己的中点
```html
.self {
   position:relative;
   left:50%;
   margin-left:-250px;
}
<div class="parent">
  <span class="self" style="float: left;width: 500px;">我是要居中的浮动元素</span>
</div>
```

#### 没给宽度的
披上一层浮动元素即可
```html
<div class=real-father>
  <div class=fake>
      <p class=son>我是浮动的我也是居中的</p>
  </div>
</div>
/* .fake 这一层是披上的，没有内容的，在外一层才是原先的父元素*/
.fake {
    float:left;
    position:relative;
    left:50%;
}
.son {
    float:left;
    position:relative;
    right:50%;
}
```

## 参考

[https://github.com/ljianshu/Blog/issues/29](url)
